#ifndef MAXPOOL_INFO_H_
#define MAXPOOL_INFO_H_

#define CHANNELS_MAXPOOL_0 128
#define HEIGHT_MAXPOOL_0 20
#define WIDTH_MAXPOOL_0 20
#define KERNEL_SIZE_MAXPOOL_0 5
#define PAD_MAXPOOL_0 2
#define STRIDE_MAXPOOL_0 1
#define ZERO_POINT_MAXPOOL_0 -119

#define CHANNELS_MAXPOOL_1 128
#define HEIGHT_MAXPOOL_1 20
#define WIDTH_MAXPOOL_1 20
#define KERNEL_SIZE_MAXPOOL_1 5
#define PAD_MAXPOOL_1 2
#define STRIDE_MAXPOOL_1 1
#define ZERO_POINT_MAXPOOL_1 -119

#define CHANNELS_MAXPOOL_2 128
#define HEIGHT_MAXPOOL_2 20
#define WIDTH_MAXPOOL_2 20
#define KERNEL_SIZE_MAXPOOL_2 5
#define PAD_MAXPOOL_2 2
#define STRIDE_MAXPOOL_2 1
#define ZERO_POINT_MAXPOOL_2 -119

#endif